springfox.documentation.swagger.v2.path: /api-docs
spring.jackson.date-format: com.example.demo.swagger.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
spring.jackson.parser.ALLOW_UNQUOTED_CONTROL_CHARS: true
spring:
  profiles:
    active: local
