package com.example.demo.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class TClick implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_click.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_click.video_id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_click.chick_rate
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer chickRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_click.modify_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_click.id
     *
     * @return the value of t_click.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_click.id
     *
     * @param id the value for t_click.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_click.video_id
     *
     * @return the value of t_click.video_id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_click.video_id
     *
     * @param videoId the value for t_click.video_id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_click.chick_rate
     *
     * @return the value of t_click.chick_rate
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getChickRate() {
        return chickRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_click.chick_rate
     *
     * @param chickRate the value for t_click.chick_rate
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setChickRate(Integer chickRate) {
        this.chickRate = chickRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_click.modify_time
     *
     * @return the value of t_click.modify_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_click.modify_time
     *
     * @param modifyTime the value for t_click.modify_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TClick other = (TClick) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getVideoId() == null ? other.getVideoId() == null : this.getVideoId().equals(other.getVideoId()))
            && (this.getChickRate() == null ? other.getChickRate() == null : this.getChickRate().equals(other.getChickRate()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getVideoId() == null) ? 0 : getVideoId().hashCode());
        result = prime * result + ((getChickRate() == null) ? 0 : getChickRate().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        return result;
    }
}