package com.example.demo.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class TMember implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.account
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.password
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.name
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.sex
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.id_num
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.mobile
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.email
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.role
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.create_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.del
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.id
     *
     * @return the value of t_member.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.id
     *
     * @param id the value for t_member.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.account
     *
     * @return the value of t_member.account
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.account
     *
     * @param account the value for t_member.account
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.password
     *
     * @return the value of t_member.password
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.password
     *
     * @param password the value for t_member.password
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.name
     *
     * @return the value of t_member.name
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.name
     *
     * @param name the value for t_member.name
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.sex
     *
     * @return the value of t_member.sex
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.sex
     *
     * @param sex the value for t_member.sex
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.id_num
     *
     * @return the value of t_member.id_num
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.id_num
     *
     * @param idNum the value for t_member.id_num
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.mobile
     *
     * @return the value of t_member.mobile
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.mobile
     *
     * @param mobile the value for t_member.mobile
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.email
     *
     * @return the value of t_member.email
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.email
     *
     * @param email the value for t_member.email
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.role
     *
     * @return the value of t_member.role
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.role
     *
     * @param role the value for t_member.role
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.create_time
     *
     * @return the value of t_member.create_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.create_time
     *
     * @param createTime the value for t_member.create_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.del
     *
     * @return the value of t_member.del
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.del
     *
     * @param del the value for t_member.del
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TMember other = (TMember) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getIdNum() == null ? other.getIdNum() == null : this.getIdNum().equals(other.getIdNum()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getIdNum() == null) ? 0 : getIdNum().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        return result;
    }
}