package com.example.demo.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class TVideo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.name
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.address
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.type
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.member_id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.upload_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.del
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.suffix
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.alias
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.id
     *
     * @return the value of t_video.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.id
     *
     * @param id the value for t_video.id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.name
     *
     * @return the value of t_video.name
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.name
     *
     * @param name the value for t_video.name
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.address
     *
     * @return the value of t_video.address
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.address
     *
     * @param address the value for t_video.address
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.type
     *
     * @return the value of t_video.type
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.type
     *
     * @param type the value for t_video.type
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.member_id
     *
     * @return the value of t_video.member_id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.member_id
     *
     * @param memberId the value for t_video.member_id
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.upload_time
     *
     * @return the value of t_video.upload_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.upload_time
     *
     * @param uploadTime the value for t_video.upload_time
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.del
     *
     * @return the value of t_video.del
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.del
     *
     * @param del the value for t_video.del
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.suffix
     *
     * @return the value of t_video.suffix
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.suffix
     *
     * @param suffix the value for t_video.suffix
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.alias
     *
     * @return the value of t_video.alias
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.alias
     *
     * @param alias the value for t_video.alias
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TVideo other = (TVideo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getMemberId() == null ? other.getMemberId() == null : this.getMemberId().equals(other.getMemberId()))
            && (this.getUploadTime() == null ? other.getUploadTime() == null : this.getUploadTime().equals(other.getUploadTime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getSuffix() == null ? other.getSuffix() == null : this.getSuffix().equals(other.getSuffix()))
            && (this.getAlias() == null ? other.getAlias() == null : this.getAlias().equals(other.getAlias()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:59:17 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getMemberId() == null) ? 0 : getMemberId().hashCode());
        result = prime * result + ((getUploadTime() == null) ? 0 : getUploadTime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getSuffix() == null) ? 0 : getSuffix().hashCode());
        result = prime * result + ((getAlias() == null) ? 0 : getAlias().hashCode());
        return result;
    }
}