package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.domain.TClick;
import com.example.demo.mybatis.domain.TClickQuery;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface TClickMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int countByExample(TClickQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByExample(TClickQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insert(TClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insertSelective(TClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    List<TClick> selectByExample(TClickQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    TClick selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") TClick record, @Param("example") TClickQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExample(@Param("record") TClick record, @Param("example") TClickQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(TClick record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_click
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKey(TClick record);
}