package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.domain.TComment;
import com.example.demo.mybatis.domain.TCommentQuery;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface TCommentMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int countByExample(TCommentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByExample(TCommentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insert(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insertSelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    List<TComment> selectByExample(TCommentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    TComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") TComment record, @Param("example") TCommentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExample(@Param("record") TComment record, @Param("example") TCommentQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKey(TComment record);
}