package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.domain.TMember;
import com.example.demo.mybatis.domain.TMemberQuery;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface TMemberMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int countByExample(TMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByExample(TMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insert(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insertSelective(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    List<TMember> selectByExample(TMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    TMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") TMember record, @Param("example") TMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExample(@Param("record") TMember record, @Param("example") TMemberQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(TMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_member
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKey(TMember record);
}