package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.domain.TRole;
import com.example.demo.mybatis.domain.TRoleQuery;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface TRoleMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int countByExample(TRoleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByExample(TRoleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insert(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insertSelective(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    List<TRole> selectByExample(TRoleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    TRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") TRole record, @Param("example") TRoleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExample(@Param("record") TRole record, @Param("example") TRoleQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(TRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKey(TRole record);
}