package com.example.demo.mybatis.mapper;

import com.example.demo.mybatis.domain.TVideo;
import com.example.demo.mybatis.domain.TVideoQuery;
import org.apache.ibatis.annotations.Param;

import java.io.Serializable;
import java.util.List;

public interface TVideoMapper <T,Q,PK extends Serializable> extends CommonMapper<T, Q,PK>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int countByExample(TVideoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByExample(TVideoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insert(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int insertSelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    List<TVideo> selectByExample(TVideoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    TVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") TVideo record, @Param("example") TVideoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByExample(@Param("record") TVideo record, @Param("example") TVideoQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKeySelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_video
     *
     * @mbggenerated Sat Apr 28 10:11:28 CST 2018
     */
    int updateByPrimaryKey(TVideo record);
}